import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Header from "../layouts/Header/Header";
import Footer from "../layouts/Footer/Footer";
import ChatbotIcon from '../components/layout/ChatbotIcon';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main>{children}</main>
        <Footer />

        <div className="flex justify-between items-center fixed z-9999999 bottom-6 left-5 right-5">
          <div className="booking-button"></div>
          <ChatbotIcon/>
        </div>
      </body>
    </html>
  );
}