import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import Header from "../layouts/Header/Header";
import Footer from "../layouts/Footer/Footer";
import ChatbotIcon from '../components/layout/ChatbotIcon';
import "sweetalert2/dist/sweetalert2.min.css";
import LanguageCurrencySettings from "../components/layout/LanguageCurrencySettings";
import LayoutProvider from "../components/layout/LayoutProvider";
import DirectionProvider from "../components/shared/DirectionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LayoutProvider>

        <DirectionProvider>
          <Header />
          <main>{children}</main>
          <Footer />

          <div className="flex justify-between items-end fixed z-[9999999] bottom-6 left-5 right-5 pointer-events-none">
            <div className="booking-button">
              <LanguageCurrencySettings/>
            </div>
            <ChatbotIcon/>
          </div>
        </DirectionProvider>
        </LayoutProvider>
      </body>
    </html>
  );
}